-- File: 02_indexes.sql
-- Separate indexes for filtering, search, and geographic queries.
USE dalilak_db;

CREATE INDEX idx_users_role_status ON users (role, status);
CREATE INDEX idx_users_deleted_at ON users (deleted_at);
CREATE INDEX idx_countries_active ON countries (is_active);
CREATE INDEX idx_cities_country ON cities (country_id);
CREATE INDEX idx_cities_active ON cities (is_active);
CREATE INDEX idx_areas_city ON areas (city_id);
CREATE INDEX idx_areas_parent ON areas (parent_area_id);
CREATE INDEX idx_areas_active ON areas (is_active);
CREATE INDEX idx_categories_parent ON categories (parent_category_id);
CREATE INDEX idx_categories_active ON categories (is_active);
CREATE INDEX idx_places_area ON places (area_id);
CREATE INDEX idx_places_status ON places (publication_status, deleted_at);
CREATE INDEX idx_places_featured ON places (is_featured, publication_status);
CREATE INDEX idx_places_verified ON places (is_verified, publication_status);
CREATE INDEX idx_places_rating ON places (average_rating, review_count);
CREATE INDEX idx_places_created_by ON places (created_by);
CREATE INDEX idx_places_deleted_at ON places (deleted_at);
CREATE SPATIAL INDEX spx_places_location ON places (place_location);
CREATE FULLTEXT INDEX ft_places_search ON places (name_ar, name_en, description_ar, description_en);
CREATE INDEX idx_place_categories_category ON place_categories (category_id, place_id);
CREATE INDEX idx_place_categories_primary ON place_categories (place_id, is_primary);
CREATE INDEX idx_place_images_order ON place_images (place_id, display_order);
CREATE INDEX idx_place_images_primary ON place_images (place_id, is_primary);
CREATE INDEX idx_place_images_deleted ON place_images (deleted_at);
CREATE INDEX idx_opening_hours_day ON opening_hours (place_id, day_of_week);
CREATE INDEX idx_amenities_active ON amenities (is_active);
CREATE INDEX idx_amenities_name_ar ON amenities (name_ar);
CREATE INDEX idx_place_amenities_amenity ON place_amenities (amenity_id, place_id);
CREATE INDEX idx_place_contacts_type ON place_contacts (place_id, contact_type);
CREATE INDEX idx_place_contacts_primary ON place_contacts (place_id, is_primary);
CREATE INDEX idx_place_contacts_deleted ON place_contacts (deleted_at);
CREATE INDEX idx_tags_active ON tags (is_active);
CREATE INDEX idx_tags_name_ar ON tags (name_ar);
CREATE INDEX idx_place_tags_tag ON place_tags (tag_id, place_id);
CREATE INDEX idx_reviews_place_status ON reviews (place_id, status);
CREATE INDEX idx_reviews_user ON reviews (user_id);
CREATE INDEX idx_reviews_rating ON reviews (place_id, rating);
CREATE INDEX idx_reviews_deleted ON reviews (deleted_at);
CREATE INDEX idx_favorites_place ON favorites (place_id, user_id);
CREATE INDEX idx_place_views_place_time ON place_views (place_id, viewed_at);
CREATE INDEX idx_place_views_user_time ON place_views (user_id, viewed_at);
CREATE INDEX idx_place_views_time ON place_views (viewed_at);
CREATE INDEX idx_interactions_user_time ON user_interactions (user_id, created_at);
CREATE INDEX idx_interactions_place_type ON user_interactions (place_id, interaction_type, created_at);
CREATE INDEX idx_place_reports_status ON place_reports (status, created_at);
CREATE INDEX idx_place_reports_place ON place_reports (place_id);
CREATE INDEX idx_review_reports_status ON review_reports (status, created_at);
CREATE INDEX idx_review_reports_review ON review_reports (review_id);
CREATE INDEX idx_notifications_user_read ON notifications (user_id, is_read, created_at);
CREATE INDEX idx_admin_logs_time ON admin_activity_logs (created_at);
CREATE INDEX idx_admin_logs_admin ON admin_activity_logs (admin_user_id, created_at);
CREATE INDEX idx_admin_logs_entity ON admin_activity_logs (entity_type, entity_id);
