version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: dalilak_mysql_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: admin_password
      MYSQL_DATABASE: dalilak_db
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin:5.2
    container_name: dalilak_db_manager
    restart: always
    ports:
      - "8080:80"
    environment:
      PMA_HOST: db
      PMA_PORT: 3306

volumes:
  mysql_data:
