# -*- coding: utf-8 -*-
TEST_BANK_V2 = [
    {'intent': 'search_by_text', 'question': 'بدي قهوة بمكان هادي أذاكر فيه بعيد عن الزحمة'},
    {'intent': 'search_by_text', 'question': 'وين ممكن آخذ صحابي أجانب يشوفوا شي مميز بعمان؟'},
    {'intent': 'search_by_text', 'question': 'بدي مكان مناسب لجلسة عمل مع فريقي'},
    {'intent': 'search_by_text', 'question': 'Where can I get authentic Jordanian mansaf?'},
    {'intent': 'search_by_text', 'question': 'مكان حلو للتصوير قبل الغروب'},
    {'intent': 'search_by_text', 'question': 'بدي أطلع بروح لحالي أفكر شوي'},
    {'intent': 'search_by_text', 'question': 'فين أقدر آخذ أطفالي يلعبوا يوم الجمعة'},
    {'intent': 'search_by_text', 'question': 'Any recommendations for a first date spot?'},
    {'intent': 'search_by_text', 'question': 'بدي مكان فخم لحفلة تخرج'},
    {'intent': 'search_by_text', 'question': 'وين ممكن أمشي وأتريّق الصبح بعمان'},
    {'intent': 'filter_by_category', 'question': 'عندكم كل المطاعم المسجلة؟ وريني ياها', 'category': 'مطاعم'},
    {'intent': 'filter_by_category', 'question': 'بدي قائمة بكل الكافيهات الموجودة', 'category': 'كافيهات'},
    {'intent': 'filter_by_category', 'question': 'شو كل الحدائق الموجودة عندكم؟', 'category': 'حدائق'},
    {'intent': 'filter_by_category', 'question': 'عرضيلي جميع المولات المسجلة', 'category': 'مولات'},
    {'intent': 'filter_by_category', 'question': 'بدي أشوف كل المتاحف يلي عندكم بالنظام', 'category': 'متاحف'},
    {'intent': 'filter_by_category', 'question': 'وريني كل المساجد والأماكن الدينية الموجودة', 'category': 'مساجد و اماكن دينية'},
    {'intent': 'filter_by_category', 'question': 'شو عندكم أسواق شعبية؟ ابغى اشوفها كلها', 'category': 'اسواق شعبية'},
    {'intent': 'filter_by_category', 'question': 'عندكم كل الأماكن المائية؟ وريني ياها', 'category': 'الأماكن المائية'},
    {'intent': 'filter_by_category', 'question': 'بدي كل الأماكن الأثرية الموجودة عندكم', 'category': 'اماكن أثرية'},
    {'intent': 'filter_by_category', 'question': 'وريني جميع ملاعب كرة القدم المسجلة', 'category': 'اماكن كرة قدم (رياضة)'},
    {'intent': 'filter_by_category', 'question': 'شو كل المزارع الموجودة بالقائمة؟', 'category': 'مزارع'},
    {'intent': 'filter_by_category', 'question': 'عندكم كل المسابح؟ وريني ياها', 'category': 'مسابح'},
    {'intent': 'filter_by_category', 'question': 'بدي أشوف كل أماكن الملاهي المتوفرة', 'category': 'ملاهي'},
    {'intent': 'filter_by_category', 'question': 'وريني جميع الشوارع والمناطق السياحية عندكم', 'category': 'شوارع ومناطق سياحية'},
    {'intent': 'get_recommendations', 'question': 'عجبتني حدائق الملك عبدالله الثاني، شو تقترح كمان؟'},
    {'intent': 'get_recommendations', 'question': 'رحت متحف السيارات الملكي وحبيته، في متاحف زيه؟'},
    {'intent': 'get_recommendations', 'question': 'جربت سوق جارا وطلع حلو، أماكن شبيهة فيه؟'},
    {'intent': 'get_recommendations', 'question': 'لو عجبتني مزرعة روساريو وين ممكن أروح كمان؟'},
    {'intent': 'get_recommendations', 'question': 'Any places similar to Jordan Museum?'},
    {'intent': 'get_recommendations', 'question': 'أماكن بتشبه قلعة عمان'},
    {'intent': 'get_recommendations', 'question': 'عجبني نادي عمان لكرة القدم، شو في أماكن رياضية متله؟'},
    {'intent': 'get_recommendations', 'question': 'جربت ذا أوك كافيه وحبيته، اقترحلي كافيهات زيه'},
    {'intent': 'nearby_search', 'question': 'أقرب متحف لجبل عمان'},
    {'intent': 'nearby_search', 'question': 'وين أقرب سوق شعبي لوسط البلد؟'},
    {'intent': 'nearby_search', 'question': 'بدي مسبح قريب من خلدا'},
    {'intent': 'nearby_search', 'question': 'أقرب مول لتلاع العلي'},
    {'intent': 'nearby_search', 'question': 'في مزرعة قريبة من دابوق؟'},
    {'intent': 'nearby_search', 'question': 'Nearest mosque to Jabal Al-Hussein'},
    {'intent': 'nearby_search', 'question': 'أقرب ملعب كرة قدم للجبيهة'},
    {'intent': 'nearby_search', 'question': 'وين أقرب حديقة لصويلح؟'},
    {'intent': 'place_info', 'question': 'كم تقييم متحف الأردن؟'},
    {'intent': 'place_info', 'question': 'شو رأيك بسوق جارا، منيح؟'},
    {'intent': 'place_info', 'question': 'عنوان قلعة عمان وين بالضبط؟'},
    {'intent': 'place_info', 'question': 'رقم هاتف تاج مول شو؟'},
    {'intent': 'place_info', 'question': 'هل حدائق الملك عبدالله الثاني مفتوحة يوم الاثنين؟'},
    {'intent': 'place_info', 'question': 'احكيلي عن مزرعة سكاي فارم'},
    {'intent': 'place_info', 'question': "What's the rating of City Mall?"},
    {'intent': 'place_info', 'question': 'لونا بارك مفتوح يوم السبت؟'},
    {'intent': 'filter_by_price', 'question': 'وريني كل الحدائق الرخيصة عندكم'},
    {'intent': 'filter_by_price', 'question': 'عندكم كافيهات بسعر متوسط؟ وريني ياها'},
    {'intent': 'filter_by_price', 'question': 'بدي أماكن مائية غالية، شو عندكم؟'},
    {'intent': 'filter_by_price', 'question': 'شو كل المتاحف الرخيصة الموجودة؟'},
    {'intent': 'filter_by_price', 'question': 'عندكم كل المولات الفخمة؟ وريني ياها'},
    {'intent': 'combined_search', 'question': 'كافيه متوسط السعر قريب من الصويفية مفتوح يوم الجمعة'},
    {'intent': 'combined_search', 'question': 'بدي متحف رخيص قريب من جبل عمان'},
    {'intent': 'combined_search', 'question': 'مول غالي قريب من خلدا'},
    {'intent': 'combined_search', 'question': 'مسجد قريب من الرابية مفتوح يوم الاحد'},
    {'intent': 'combined_search', 'question': 'مسبح غالي قريب من الجبيهة'},
    {'intent': 'combined_search', 'question': 'سوق شعبي متوسط السعر قريب من ماركا مفتوح يوم السبت'},
    {'intent': None, 'question': 'شو أفضل تمرين لعضلة البطن؟'},
    {'intent': None, 'question': 'احكيلي معلومة غريبة عن الفضاء'},
    {'intent': None, 'question': 'مين لاعب كرة القدم الأفضل بالتاريخ برأيك؟'},
    {'intent': None, 'question': "What's the boiling point of water in Fahrenheit?"},
    {'intent': None, 'question': 'اكتبلي رسالة اعتذار لصديقي'},
    {'intent': None, 'question': 'شو معنى كلمة Nostalgia؟'},
    {'intent': None, 'question': 'كيف أسوي بايثون فيرتشوال إنفايرومنت؟'},
    {'intent': None, 'question': 'هل الأردن بلد آمن للسياحة؟'},
    {'intent': 'search_by_text', 'question': 'بديش مطعم، بدي مكان فيه طبيعة بس'},
    {'intent': 'search_by_text', 'question': 'متحف'},
    {'intent': 'search_by_text', 'question': '😍 بدي مكان حلو اليوم ضروري ضروري'},
    {'intent': 'search_by_text', 'question': 'مزرعه مزرعه مزرعه'},
    {'intent': 'place_info', 'question': 'شو رأيك بحدائق الحسين، حلوة ولا لأ؟'},
    {'intent': None, 'question': 'ليش سوق جارا مشهور هيك؟'},
    {'intent': None, 'question': '                    '},
    {'intent': None, 'question': 'مرحبا'},
    {'intent': None, 'question': '12345'},
    {'intent': 'filter_by_category', 'question': 'بدي أشوف كل ألمولاات الموجوده عندكم', 'category': 'مولات'},
    {'intent': None, 'question': 'متحف الأردن قريب من جبل عمان؟'},
    {'intent': 'get_recommendations', 'question': 'قلعة عمان عجبتني كتير، في متلها؟'},
    {'intent': 'place_info', 'question': 'تاج مول تقييمه كم من 5؟'},
    {'intent': 'search_by_text', 'question': "I need a place for my mom's birthday, nothing too loud"},
    {'intent': None, 'question': 'شو الفرق بين الشاي الأخضر والأسود؟'},
    {'intent': 'filter_by_category', 'question': 'شو الأماكن الدينية الموجودة عندكم بالضبط ومو الجوامع بس', 'category': 'مساجد و اماكن دينية'},
    {'intent': 'search_by_text', 'question': 'بدور على مطعم إيطالي كويس'},
    {'intent': None, 'question': 'احكيلي كم عدد سكان الأردن'},
    {'intent': 'compound_query', 'question': 'عجبني مطعم ليفانت وبعدين قول لي حدائق قريبة منه'},
    {'intent': 'compound_query', 'question': 'جربت سوق جارا وطلعت حلوة وبعدين احكيلي عن كافيهات قريبة منها'},
    {'intent': 'compound_query', 'question': 'عجبتني حدائق الحسين وبعدين قول لي مطاعم قريبة منها'},
    {'intent': 'compound_query', 'question': 'احكيلي عن متحف الأردن وبعدين قول لي كافيهات قريبة منه'},
    {'intent': 'compound_query', 'question': 'شو رأيك بتاج مول وبعدين احكيلي عن مطاعم قريبة منه'},
    {'intent': 'compound_query', 'question': 'وريني كل المتاحف وبعدين قول لي تقييم متحف الأردن'},
    {'intent': 'compound_query', 'question': 'أقرب مول لخلدا وبعدين احكيلي عن كافيهات قريبة منه'},
    {'intent': 'compound_query', 'question': 'عجبني لونا بارك وبعدين قول لي مطاعم قريبة منه'},
    {'intent': 'compound_query', 'question': 'عجبني مطعم ليفانت وبعدين احكيلي عن كافيهات قريبة من عبدون'},
    {'intent': 'compound_query', 'question': 'شو رأيك بحدائق الحسين وبعدين قول لي مسابح قريبة منها'},
]

NEW_CASES_V3 = [
    {'intent': 'filter_by_category', 'question': 'عندي فضول، عرضيلي كل المطعمين المسجلين عندكم', 'category': 'مطاعم'},
    {'intent': 'filter_by_category', 'question': 'بدي قائمة بكل أماكن الأكل الموجودة', 'category': 'مطاعم'},
    {'intent': 'filter_by_category', 'question': 'Show me all the restaurants you have', 'category': 'مطاعم'},
    {'intent': 'filter_by_category', 'question': 'وريني جميع الكوفيات يلي عندكم', 'category': 'كافيهات'},
    {'intent': 'filter_by_category', 'question': 'Show me all the coffee shops you have', 'category': 'كافيهات'},
    {'intent': 'filter_by_category', 'question': 'بدي أشوف كل المتنزهات الموجودة بالنظام', 'category': 'حدائق'},
    {'intent': 'filter_by_category', 'question': 'عندكم كل المتنزهات؟ وريني ياها', 'category': 'حدائق'},
    {'intent': 'filter_by_category', 'question': 'عندكم كل مراكز التسوق؟ وريني ياها الموجودة', 'category': 'مولات'},
    {'intent': 'filter_by_category', 'question': 'List all the shopping centers you have', 'category': 'مولات'},
    {'intent': 'filter_by_category', 'question': 'شو كل المتاحف يلي مسجلة بالنظام؟', 'category': 'متاحف'},
    {'intent': 'filter_by_category', 'question': 'Show me all the museums you have registered', 'category': 'متاحف'},
    {'intent': 'filter_by_category', 'question': 'عندكم كل الجوامع؟ وريني ياها', 'category': 'مساجد و اماكن دينية'},
    {'intent': 'filter_by_category', 'question': 'بدي أشوف كل الكنائس الموجودة عندكم', 'category': 'مساجد و اماكن دينية'},
    {'intent': 'filter_by_category', 'question': 'وريني جميع الأماكن الدينية المتوفرة', 'category': 'مساجد و اماكن دينية'},
    {'intent': 'filter_by_category', 'question': 'شو عندكم بازارات؟ ابغى اشوفها كلها', 'category': 'اسواق شعبية'},
    {'intent': 'filter_by_category', 'question': 'Show me all the souqs you have', 'category': 'اسواق شعبية'},
    {'intent': 'filter_by_category', 'question': 'بدي كل الألعاب المائية الموجودة عندكم', 'category': 'الأماكن المائية'},
    {'intent': 'filter_by_category', 'question': 'عندكم كل الأماكن التاريخية؟ وريني ياها', 'category': 'اماكن أثرية'},
    {'intent': 'filter_by_category', 'question': 'Show me all the archaeological sites you have', 'category': 'اماكن أثرية'},
    {'intent': 'filter_by_category', 'question': 'وريني جميع ملاعب الكورة المسجلة', 'category': 'اماكن كرة قدم (رياضة)'},
    {'intent': 'filter_by_category', 'question': 'عندكم كل الأماكن الرياضية؟ وريني ياها', 'category': 'اماكن كرة قدم (رياضة)'},
    {'intent': 'filter_by_category', 'question': 'شو كل المزارع الموجودة بالقائمة عندكم بالضبط؟', 'category': 'مزارع'},
    {'intent': 'filter_by_category', 'question': 'List all the farms you have', 'category': 'مزارع'},
    {'intent': 'filter_by_category', 'question': 'Show me all the pools you have', 'category': 'مسابح'},
    {'intent': 'filter_by_category', 'question': 'عندكم كل الملاهي؟ وريني ياها بالكامل', 'category': 'ملاهي'},
    {'intent': 'filter_by_category', 'question': 'وريني جميع أماكن الأراجيح الموجودة', 'category': 'ملاهي'},
    {'intent': 'filter_by_category', 'question': 'بدي قائمة بكل الشوارع السياحية المسجلة', 'category': 'شوارع ومناطق سياحية'},
    {'intent': 'filter_by_category', 'question': 'عندكم كل المناطق السياحية؟ وريني ياها', 'category': 'شوارع ومناطق سياحية'},
    {'intent': 'filter_by_price', 'question': 'وريني كل الكافيهات الرخيصة عندكم', 'category': 'كافيهات', 'price_level': 1},
    {'intent': 'filter_by_price', 'question': 'بدي أماكن أكل اقتصادية، شو عندكم؟', 'category': 'مطاعم', 'price_level': 1},
    {'intent': 'filter_by_price', 'question': 'عندكم كل المساجد الرخيصة؟', 'category': 'مساجد و اماكن دينية', 'price_level': 1},
    {'intent': 'filter_by_price', 'question': 'بدي مطاعم بسعر معقول، وريني ياها', 'category': 'مطاعم', 'price_level': 2},
    {'intent': 'filter_by_price', 'question': 'عندكم مولات بسعر متوسط؟ وريني ياها', 'category': 'مولات', 'price_level': 2},
    {'intent': 'filter_by_price', 'question': 'شو كل الملاعب متوسطة السعر؟', 'category': 'اماكن كرة قدم (رياضة)', 'price_level': 2},
    {'intent': 'filter_by_price', 'question': 'بدي مسابح فخمة، شو عندكم؟', 'category': 'مسابح', 'price_level': 3},
    {'intent': 'filter_by_price', 'question': 'عندكم كل المزارع الغالية؟ وريني ياها', 'category': 'مزارع', 'price_level': 3},
    {'intent': 'filter_by_price', 'question': 'وريني كل الملاهي الراقية عندكم', 'category': 'ملاهي', 'price_level': 3},
    {'intent': 'nearby_search', 'question': 'وين أقرب مول للشميساني؟', 'neighborhood': 'الشميساني'},
    {'intent': 'nearby_search', 'question': 'بدي كافيه قريب من عبدون', 'neighborhood': 'عبدون'},
    {'intent': 'nearby_search', 'question': 'أقرب حديقة للدوار الأول', 'neighborhood': 'الدوار الاول'},
    {'intent': 'nearby_search', 'question': 'في مطعم قريب من الدوار السابع؟', 'neighborhood': 'الدوار السابع'},
    {'intent': 'nearby_search', 'question': 'وين أقرب مسجد لجبل الحسين؟', 'neighborhood': 'جبل الحسين'},
    {'intent': 'nearby_search', 'question': 'بدي سوق شعبي قريب من الرابية', 'neighborhood': 'الرابية'},
    {'intent': 'nearby_search', 'question': 'أقرب متحف لتلاع العلي', 'neighborhood': 'تلاع العلي'},
    {'intent': 'nearby_search', 'question': 'في ملعب كرة قدم قريب من صويلح؟', 'neighborhood': 'صويلح'},
    {'intent': 'nearby_search', 'question': 'وين أقرب حديقة لوسط البلد؟', 'neighborhood': 'وسط البلد'},
    {'intent': 'nearby_search', 'question': 'بدي كافيه قريب من الصويفية', 'neighborhood': 'الصويفية'},
    {'intent': 'nearby_search', 'question': 'أقرب سوق شعبي لماركا', 'neighborhood': 'ماركا'},
    {'intent': 'nearby_search', 'question': 'في مول قريب من طبربور؟', 'neighborhood': 'طبربور'},
    {'intent': 'nearby_search', 'question': 'وين أقرب مطعم لأبو نصير؟', 'neighborhood': 'أبو نصير'},
    {'intent': 'nearby_search', 'question': 'أقرب مزرعة لدابوق', 'neighborhood': 'دابوق'},
    {'intent': 'nearby_search', 'question': 'بدي مسبح قريب من ناعور', 'neighborhood': 'ناعور'},
    {'intent': 'nearby_search', 'question': 'أقرب حديقة لمرج الحمام', 'neighborhood': 'مرج الحمام'},
    {'intent': 'nearby_search', 'question': 'Nearest mall to Khalda', 'neighborhood': 'خلدا'},
    {'intent': 'nearby_search', 'question': 'Nearest museum to Downtown', 'neighborhood': 'وسط البلد'},
    {'intent': 'nearby_search', 'question': 'Cafe near Sweifieh please', 'neighborhood': 'الصويفية'},
    {'intent': 'place_info', 'question': 'كم تقييم متحف السيارات الملكي؟', 'place': 'متحف السيارات الملكي'},
    {'intent': 'place_info', 'question': 'رقم هاتف مطعم ليفانت شو؟', 'place': 'مطعم ليفانت'},
    {'intent': 'place_info', 'question': 'عنوان سيتي مول وين بالضبط؟', 'place': 'سيتي مول'},
    {'intent': 'place_info', 'question': 'احكيلي عن مسجد الملك عبد الله', 'place': 'مسجد الملك عبد الله'},
    {'intent': 'place_info', 'question': 'هل سوق جارا مفتوح يوم السبت؟', 'place': 'سوق جارا'},
    {'intent': 'place_info', 'question': 'تفاصيل تاج مول شو ممكن تعرفيني عليها؟', 'place': 'تاج مول'},
    {'intent': 'place_info', 'question': 'Jordan Museum rating please?', 'place': 'متحف الأردن'},
    {'intent': 'place_info', 'question': 'مزرعة سكاي فارم مفتوحة يوم الجمعة؟', 'place': 'مزرعة سكاي فارم'},
    {'intent': 'place_info', 'question': 'تفاصيل عن رومي كافيه لو سمحتِ', 'place': 'رومي كافيه'},
    {'intent': 'place_info', 'question': 'كم تقييم العبدلي مول؟', 'place': 'العبدلي مول'},
    {'intent': 'place_info', 'question': 'Address of Royal Automobile Museum please', 'place': 'متحف السيارات الملكي'},
    {'intent': 'place_info', 'question': 'مسبح المدينة المغطى مفتوح يوم الاثنين؟', 'place': 'مسبح المدينة المغطى'},
    {'intent': 'get_recommendations', 'question': 'رشحلي أماكن متل متحف السيارات الملكي'},
    {'intent': 'get_recommendations', 'question': 'جربت مطعم ليفانت وعجبني كتير، في متله؟'},
    {'intent': 'get_recommendations', 'question': 'لو حبيت تاج مول وين بعد ممكن أروح؟'},
    {'intent': 'get_recommendations', 'question': 'عجبتني حدائق الحسين، شو تقترح كمان؟'},
    {'intent': 'get_recommendations', 'question': 'أماكن بتشبه سوق الوحدات الشعبي'},
    {'intent': 'get_recommendations', 'question': 'Any places similar to Luna park?'},
    {'intent': 'get_recommendations', 'question': 'قترحلي كافيهات متل ذا أوك كافيه'},
    {'intent': 'get_recommendations', 'question': 'عجبني نادي عمان لكرة القدم، في متله؟'},
    {'intent': 'combined_search', 'question': 'بدي مطعم مفتوح يوم الجمعة'},
    {'intent': 'combined_search', 'question': 'كافيه رخيص مفتوح يوم السبت'},
    {'intent': 'combined_search', 'question': 'بدي مكان قريب من الشميساني مفتوح يوم الاحد'},
    {'intent': 'combined_search', 'question': 'بدي مول فخم قريب من خلدا'},
    {'intent': 'combined_search', 'question': 'مطعم رخيص قريب من عبدون'},
    {'intent': 'combined_search', 'question': 'كافيه متوسط السعر قريب من تلاع العلي'},
    {'intent': 'combined_search', 'question': 'مسجد مفتوح يوم الجمعة قريب من الرابية'},
    {'intent': 'combined_search', 'question': 'مسبح غالي قريب من الجبيهة مفتوح يوم السبت'},
    {'intent': 'combined_search', 'question': 'مطعم متوسط السعر مفتوح يوم الخميس'},
    {'intent': 'combined_search', 'question': 'بدي حديقة مفتوحة يوم الاثنين قريبة من وسط البلد'},
    {'intent': 'compound_query', 'question': 'احكيلي عن متحف السيارات الملكي وبعدين احكيلي عن كافيهات قريبة منه'},
    {'intent': 'compound_query', 'question': 'شو رأيك بسوق جارا وبعدين قول لي مطاعم قريبة منه'},
    {'intent': 'compound_query', 'question': 'عجبني رومي كافيه وبعدين قول لي حدائق قريبة منه'},
    {'intent': 'compound_query', 'question': 'بدي أشوف كل المتاحف وكمان قول لي تقييم متحف الأردن'},
    {'intent': 'compound_query', 'question': 'أقرب مطعم لعبدون وبعدين احكيلي عن كافيهات قريبة منه'},
    {'intent': 'compound_query', 'question': 'عجبتني حدائق الملك عبدالله الثاني وكمان احكيلي عن مطاعم قريبة منها'},
    {'intent': 'compound_query', 'question': 'تاج مول تقييمه كم and then tell me about cafes near it'},
    {'intent': 'compound_query', 'question': 'عجبني سيتي مول وبعدين قول لي مطاعم قريبة منه'},
    {'intent': 'search_by_text', 'question': 'بدي قعدة هادية بعيد عن الضجة'},
    {'intent': 'search_by_text', 'question': 'وين أقدر آخذ صحابي الأجانب يوم الجمعة يشوفوا شي تراثي؟'},
    {'intent': 'search_by_text', 'question': 'مكان مريح أقرا فيه كتاب'},
    {'intent': 'search_by_text', 'question': 'Where can I try local Jordanian sweets?'},
    {'intent': 'search_by_text', 'question': 'بدي مكان أحتفل فيه بعيد ميلاد صغير'},
    {'intent': 'search_by_text', 'question': 'أبغى مكان يصور فيه أهل انستغرام'},
    {'intent': 'search_by_text', 'question': 'Something chill for a Friday evening with friends'},
    {'intent': 'search_by_text', 'question': 'وين ممكن أطلع مع عيلتي يوم العطلة'},
    {'intent': 'search_by_text', 'question': 'بدي مكان يناسب كبار السن يمشوا فيه بهدوء'},
    {'intent': 'search_by_text', 'question': 'Good spot to watch the sunset in Amman'},
    {'intent': None, 'question': 'شو أحسن طريقة أتعلم فيها بايثون بسرعة؟'},
    {'intent': None, 'question': 'احكيلي نكتة قصيرة'},
    {'intent': None, 'question': 'كم عدد الكواكب بالمجموعة الشمسية؟'},
    {'intent': None, 'question': 'What is 15% of 200?'},
    {'intent': None, 'question': 'ساعدني أحسب متوسط ثلاث درجات: 85, 90, 78'},
    {'intent': None, 'question': 'مين مخترع المصباح الكهربائي؟'},
    {'intent': None, 'question': 'اكتبلي دعوة لحفلة تخرج'},
    {'intent': None, 'question': 'What is the difference between AI and machine learning?'},
    {'intent': None, 'question': 'كيف اسوي حساب بنكي بالأردن؟'},
    {'intent': 'filter_by_category', 'question': 'عندكم    كل    المتاحف   ', 'category': 'متاحف'},
    {'intent': 'filter_by_category', 'question': 'عَنْدَكُمْ كُلّ الْمَطَاعِمِ', 'category': 'مطاعم'},
    {'intent': None, 'question': 'مطعمممممم'},
    {'intent': None, 'question': '😂😂😂'},
    {'intent': None, 'question': '...'},
    {'intent': None, 'question': '؟؟؟؟؟'},
    {'intent': None, 'question': 'ok'},
    {'intent': None, 'question': 'test test test'},
]

KNOWN_BUG_REGRESSION_CASES = [
    {'intent': 'nearby_search', 'question': 'في ملعب كرة قدم قريب من الجامعة الأردنية؟', 'note': 'كان يترجّح غلط لمسجد قبل الإصلاح'},
    {'intent': 'place_info', 'question': "What's the rating of Jordan Museum?", 'note': "كان يرجّح غلط 'مسجد الجامعة الأردنية' قبل الإصلاح"},
]

TEST_BANK_V3 = TEST_BANK_V2 + NEW_CASES_V3

if __name__ == "__main__":
    from collections import Counter
    print("عدد أسئلة v2 الأصلية:", len(TEST_BANK_V2))
    print("عدد الأسئلة الجديدة المضافة بـ v3:", len(NEW_CASES_V3))
    print("عدد أسئلة v3 الكلي (v2 + الجديد):", len(TEST_BANK_V3))
    print("عدد حالات تثبيت الإصلاح (منفصلة):", len(KNOWN_BUG_REGRESSION_CASES))
    print(Counter(c["intent"] for c in TEST_BANK_V3))